export const SEND_MESSAGE = "SEND_MESSAGE"
export const UPDATE_MESSAGE_LIST = "UPDATE_MESSAGE_LIST"
export const UPDATE_ONLINE_COUNT = "UPDATE_ONLINE_COUNT"

export const WS_CONNECT = "WS_CONNECT"
export const WS_CONNECTED = "WS_CONNECTED"
export const WS_DISCONNECT = "WS_DISCONNECT"
export const WS_DISCONNECTED = "WS_DISCONNECTED"
export const WS_RECONNECTING = "WS_RECONNECTING"


